services:
  anaconda:
    image: continuumio/anaconda3
    volumes:
      - ./notebooks:/opt/notebooks
    ports:
      - "8888:8888"
    command: bash -c "
      conda install jupyter -y --quiet
      && conda install jupyter -y --quiet 
      && mkdir -p /opt/notebooks
      && jupyter notebook 
      --notebook-dir=/opt/notebooks --ip='*' --port=8888 
      --no-browser --allow-root
      "